name: dependency-updates

on:
  push:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:          
  repos-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: update repos
        run: | 
         rm -rf assets/elements/repos
         mkdir assets/elements/repos
         for repo in $(curl -skL https://api.github.com/orgs/ZoeyVid/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".[].name" | grep -v .github | sort); do curl -skL https://raw.githubusercontent.com/$repo/$(curl -skL "https://api.github.com/repos/ZoeyVid/$repo" --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".default_branch")/README.md -o assets/elements/repos/$repo.md; done;
         echo { | tee -a assets/elements/repos/repos.json
         for repo in $(curl -skL https://api.github.com/orgs/ZoeyVid/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".[].name" | grep -v .github | sort); do echo \"$repo\": { \"name\": \"$repo\":, \"description\": \"$(curl -skL https://api.github.com/repos/ZoeyVid/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.description')\", \"homepage\": \"$(curl -skL https://api.github.com/repos/ZoeyVid/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.homepage')\", \"url\": \"https://zoeyvid.de/assets/elements/repos/$repo.md\"}, | tee -a assets/elements/repos/repos.json; done;
         echo } | tee -a assets/elements/repos/repos.json
         sed -i "s|null||g" assets/elements/repos/repos.json
     
      - name: push changes
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -sm "update repos"
          git push
          
  marked-update:
    needs: repos-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update marked version
        run: curl -L https://cdn.jsdelivr.net/npm/marked/marked.min.js -o assets/plugins/marked.min.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          signoff: true
          delete-branch: true
          commit-message: update marked version
          branch: update-marked-version
          title: update marked version to ${{ steps.update.outputs.version }}
          body: update marked version to ${{ steps.update.outputs.version }}

  tailwindcss-update:
    needs: marked-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update tailwindcss
        uses: ZoeyVid/tailwindcss-update@develop
        with:
          input: assets/css/input.css
          output: assets/css/output.css
          
      - name: push changes
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -sm "update tailwindcss"
          git push
          
  jquery-update:
    needs: tailwindcss-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update jquery version
        id: update
        run: |
          JQUERY_VERSION="$(
          git ls-remote --tags https://github.com/jquery/jquery \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1 \
              | sed -E "s/\^\{\}//"
          )"
          curl -L https://code.jquery.com/jquery-$JQUERY_VERSION.min.js -o assets/plugins/jquery.min.js
          echo "version=$JQUERY_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          signoff: true
          delete-branch: true
          commit-message: update jquery version to ${{ steps.update.outputs.version }}
          branch: update-jquery-version
          title: update jquery version to ${{ steps.update.outputs.version }}
          body: update jquery version to ${{ steps.update.outputs.version }}
