name: repo-update

on:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:
  repo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         ref: ${{ github.ref_name }}
        
      - name: update repos
        run: | 
         export user=ZoeyVid
         export domain=zoeyvid.de
         export path=assets/repos
         rm -rf $path
         mkdir -p $path
         for repo in $(curl -sl https://api.github.com/orgs/$user/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".[].name" | grep -v .github | grep -Pv \"\|$(curl -sl https://api.github.com/orgs/$user/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq ".[] | select(.archived==true)" | jq -r ".name" | paste -s -d "|")\|\" | sort); do echo -e "<meta charset="utf-8">\n$(curl -X POST https://api.github.com/markdown/raw --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header "Content-Type: text/plain" -d "$(curl -sl https://raw.githubusercontent.com/$user/$repo/$(curl -sl "https://api.github.com/repos/$user/$repo" --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".default_branch")/README.md)")" | tee $path/$repo.html; done;
         echo { | tee -a $path/repos.json
         for repo in $(curl -sl https://api.github.com/orgs/$user/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".[].name" | grep -v .github | grep -Pv \"\|$(curl -sl https://api.github.com/orgs/$user/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq ".[] | select(.archived==true)" | jq -r ".name" | paste -s -d "|")\|\" | sort); do echo \"$repo\": { \"name\": \"$repo\", \"html_url\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.html_url')\", \"readme\": \"https://$domain/$path/$repo.html\", \"fork\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.fork')\", \"description\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.description')\", \"homepage\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.homepage')\"}, | tee -a $path/repos.json; done;
         sed -i '$ d' $path/repos.json
         for repo in $(curl -sl https://api.github.com/orgs/$user/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r ".[].name" | grep -v .github | grep -Pv \"\|$(curl -sl https://api.github.com/orgs/$user/repos --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq ".[] | select(.archived==true)" | jq -r ".name" | paste -s -d "|")\|\" | sort -r | head -n 1); do echo \"$repo\": { \"name\": \"$repo\", \"html_url\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.html_url')\", \"readme\": \"https://$domain/$path/$repo.html\", \"fork\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.fork')\", \"description\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.description')\", \"homepage\": \"$(curl -sl https://api.github.com/repos/$user/$repo --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.homepage')\"} | tee -a $path/repos.json; done;
         echo } | tee -a $path/repos.json
         jq . $path/repos.json | tee $path/index.json
         sed -i "s|\"null\"|\"\"|g" $path/index.json
         rm -rf $path/repos.json
#         yq -P $path/index.json | tee $path/index.yaml
         
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$*"
     
      - name: push changes
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -sm "update repos"
          git push
